name: prostt5
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiodns=3.5.0=py310h06a4308_1
  - aiohappyeyeballs=2.6.1=py310h06a4308_0
  - aiohttp=3.13.2=py310hee96239_0
  - aiosignal=1.4.0=py310h06a4308_0
  - arrow=1.4.0=py310h06a4308_0
  - arrow-cpp=21.0.0=h4e7ead5_0
  - async-timeout=5.0.1=py310h06a4308_0
  - attrs=25.4.0=py310h06a4308_2
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310haa0f9ac_1
  - brotlicffi=1.1.0.0=py310hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cffi=2.0.0=py310h4eded50_1
  - chardet=5.2.0=py310h06a4308_0
  - charset-normalizer=3.4.4=py310h06a4308_0
  - cookiecutter=2.6.0=py310h06a4308_1
  - evaluate=0.4.6=py310h1d409f2_0
  - expat=2.7.3=h3385a95_0
  - frozenlist=1.8.0=py310hbdd6827_0
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - huggingface_hub=0.34.4=py310h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=py310h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - jinja2=3.1.6=py310h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.16.0=heebcbe5_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.15.0=hd8eb582_4
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=py310h06a4308_0
  - mdurl=0.1.2=py310h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py310hacdc0fc_0
  - mkl_fft=2.1.1=py310h8fe796d_0
  - mkl_random=1.3.0=py310h505adc9_0
  - multidict=6.7.0=py310hee96239_0
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.14.1=py310h41d4191_0
  - numpy-base=2.2.5=py310he1678cf_2
  - openssl=3.0.18=hd6dcaed_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=py310h06a4308_1
  - pandas=2.3.3=py310h23c847b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycares=4.10.0=py310ha137689_0
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.2=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-slugify=8.0.4=py310h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py310h5eee18b_0
  - pytz=2025.2=py310h06a4308_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_1
  - rich=14.2.0=py310h06a4308_0
  - s2n=1.5.14=hdbd6064_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=py310h7040dfc_1
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvloop=0.22.1=py310h939ff40_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py310hee96239_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - accelerate==1.11.0
      - anyio==4.11.0
      - array-api-compat==1.12.0
      - biom-format==2.1.17
      - biopython==1.86
      - certifi==2025.11.12
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.1
      - decorator==5.2.1
      - dill==0.4.0
      - einops==0.8.1
      - ete3==3.1.3
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multiprocess==0.70.18
      - natsort==8.4.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - patsy==1.0.2
      - peft==0.17.1
      - pillow==11.3.0
      - pip==25.3
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyparsing==3.2.5
      - pyyaml==6.0.3
      - regex==2025.11.3
      - safetensors==0.6.2
      - scikit-bio==0.7.1.post1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sniffio==1.3.1
      - statsmodels==0.14.5
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchvision==0.19.0+cu118
      - transformers==4.57.1
      - triton==3.0.0
      - xxhash==3.6.0
